//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Tests/Redola.Rpc.TestContracts/Hello.proto
namespace Redola.Rpc.TestContracts
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HelloRequest")]
  public partial class HelloRequest : global::ProtoBuf.IExtensible
  {
    public HelloRequest() {}
    
    private string _Text;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HelloResponse")]
  public partial class HelloResponse : global::ProtoBuf.IExtensible
  {
    public HelloResponse() {}
    
    private string _Text;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Hello10000Request")]
  public partial class Hello10000Request : global::ProtoBuf.IExtensible
  {
    public Hello10000Request() {}
    
    private string _Text;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Hello10000Response")]
  public partial class Hello10000Response : global::ProtoBuf.IExtensible
  {
    public Hello10000Response() {}
    
    private string _Text;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IHelloService
    {
      Redola.Rpc.TestContracts.HelloResponse Hello(Redola.Rpc.TestContracts.HelloRequest request);
    Redola.Rpc.TestContracts.Hello10000Response Hello10000(Redola.Rpc.TestContracts.Hello10000Request request);
    
    }
    
    
}