//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Tests/Redola.Rpc.TestContracts/Order.proto
namespace Redola.Rpc.TestContracts
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Order")]
  public partial class Order : global::ProtoBuf.IExtensible
  {
    public Order() {}
    
    private string _OrderID;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"OrderID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OrderID
    {
      get { return _OrderID; }
      set { _OrderID = value; }
    }
    private string _ItemID;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private double _BuyCount;
    [global::ProtoBuf.ProtoMember(70, IsRequired = true, Name=@"BuyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double BuyCount
    {
      get { return _BuyCount; }
      set { _BuyCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaceOrderRequest")]
  public partial class PlaceOrderRequest : global::ProtoBuf.IExtensible
  {
    public PlaceOrderRequest() {}
    
    private Redola.Rpc.TestContracts.Order _Contract;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"Contract", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Redola.Rpc.TestContracts.Order Contract
    {
      get { return _Contract; }
      set { _Contract = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaceOrderResponse")]
  public partial class PlaceOrderResponse : global::ProtoBuf.IExtensible
  {
    public PlaceOrderResponse() {}
    
    private Redola.Rpc.TestContracts.Order _Contract;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"Contract", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Redola.Rpc.TestContracts.Order Contract
    {
      get { return _Contract; }
      set { _Contract = value; }
    }
    private Redola.Rpc.TestContracts.Order _Order = null;
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"Order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Redola.Rpc.TestContracts.Order Order
    {
      get { return _Order; }
      set { _Order = value; }
    }
    private Redola.Rpc.TestContracts.PlaceOrderErrorCode _ErrorCode;
    [global::ProtoBuf.ProtoMember(70, IsRequired = true, Name=@"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Redola.Rpc.TestContracts.PlaceOrderErrorCode ErrorCode
    {
      get { return _ErrorCode; }
      set { _ErrorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlaceOrderErrorCode")]
    public enum PlaceOrderErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OrderPlaced", Value=0)]
      OrderPlaced = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownPlaceOrderError", Value=1)]
      UnknownPlaceOrderError = 1
    }
  
}